project_id = "iwmfxcrzzwpmxomydmuq"

[api]
port = 54331
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
major_version = 15

[studio]
port = 54333

[inbucket]
port = 54334

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
port = 54337